services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Kedharnath@9381
      MYSQL_DATABASE: hspmanagement
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uappuser", "-papppassword123"]
      timeout: 20s
      retries: 10

  backend:
    build: ./Backend-CICD
    container_name: spring_backend
    ports:
      - "5050:5050"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./Frontend-CICD
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: